### PR TITLE
Content and bug fixes

### LINKED ISSUE #26: List of adopted drains not showing as links
After logging in, the list of drains adopted by the current user are not shown as links.

### PR DESCRIPTION
**Pull request by roberth05**
Resolves #26 & #12

### CODE REVIEW

**Comment by roberth05** [comment]
@brandonmichaelhunter I completed the PR but it didn't resolve the issue in the live version.  Can you take another look?

**Comment by brandonmichaelhunter** [comment]
@roberth05 Will do.

**Comment by brandonmichaelhunter** [comment]
I went to the live site and after I logged in I see my adopted drains displayed as links (see below):
image

Let me know if I'm missing something.

**Comment by roberth05** [comment]
What browser are you using?

**Comment by brandonmichaelhunter** [comment]
@roberth05  I was using Chrome version 78.0.3904.97... I will try in safri now.

**Comment by brandonmichaelhunter** [comment]
Links appears in Safri for me as well.

**Comment by roberth05** [comment]
Very strange.   Might be my account. I'll try with a different account.

**Comment by roberth05** [comment]
@brandonmichaelhunter Still no good for me, even with a new account.

On my side, it looks like a zero length link is being created to the left hand side of the drain address instead of being the entire text of the address.

**Comment by brandonmichaelhunter** [comment]
@roberth05 - Hey Robert I have some time tonight to take a look at this. Please send me a screenshot of what you're seeing.

**Comment by roberth05** [comment]
See below.  It shows the render and the code I'm seeing.  Notice there is a link, but it has no text.

image

**Comment by brandonmichaelhunter** [comment]
@roberth05 can you check the database to see if there is actual text associated with the user?
Try running this query against your database:
SELECT name, lat, lng
FROM public.things a INNER JOIN public.users b ON a.user_id = b.id
WHERE email = '<user email>'

And let me know if you see values in the name field?

**Comment by roberth05** [comment]
Nice catch!  That was the issue.

**Pull request merged**
