### PR TITLE
Track cleaning

### LINKED ISSUE #20: Ability to respond/track if drain has been cleaned
Could either be through a simple link in an email or through the app.  Would allow reporting on how often drains are being cleaned.

This received the most public votes during the 8/21 meeting: 15 Strong Agreement votes

### PR DESCRIPTION
**Pull request by roberth05**
To resolve #20

### CODE REVIEW

**Comment by roberth05** [comment]
@brandonmichaelhunter Would love it if you could take a look at this before doing a final merge.

**Review by brandonmichaelhunter — APPROVED** [review]
Approved
Questions:

- How can I view my previous cleaning activities?
-

**Comment by carlvlewis** [comment]
Wow! Is this ready to merge? You guys got all that data?

**Comment by carlvlewis** [comment]
> @brandonmichaelhunter Would love it if you could take a look at this before doing a final merge.

Remember there's always version control :)

**Comment by roberth05** [comment]
> Approved
> Questions:
> 
> * How can I view my previous cleaning activities?

@brandonmichaelhunter Not functional yet.  Wanted to get the basic data collection in first.  We should add reporting/viewing/stats in another PR.

**Pull request merged**
